export const SAVE_USER_INFO    = 'SAVE_USER_INFO';
export const UPDATE_USER_STATE = 'UPDATE_USER_STATE';
export const SAVE_IMAGE_INFO   = 'SAVE_IMAGE_INFO';

// export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
// export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
