//name, question, url
const IMAGES = [
[1, "Does the image appear to be in a bathroom?", "images/1.jpg", "Yes"],
[2, "Does the color brown appear?", "images/2.jpg", "Yes"],
[3, "Is there a person in the image?", "images/3.jpg", "No"],
[4, "Is the color blue prominent in the image?", "images/4.jpg", "No"],
[5, "Is there feces in the image?", "images/5.jpg", "Yes"],
[6, "Does the image contain a person?", "images/6.jpg", "Yes"],
[7, "Are the victim's eyes open?", "images/7.jpg", "Yes"],
[8, "Is there a chair in the image?", "images/8.jpg", "No"],
[9, "Is the victim standing?", "images/9.jpg", "No"],
[10, "Are there black marks around the person's eyes?", "images/10.jpg", "Yes"],
[11, "Is the person seated?", "images/11.jpg", "Yes"],
[12, "Does the image contain a knife?", "images/12.jpg", "Yes"],
[13, "Is the person holding a gun?", "images/13.jpg", "No"],
[14, "Can you see eyes in the image?", "images/14.jpg", "No"],
[15, "Does the person appear to be in a vehicle?", "images/15.jpg", "No"],
[16, "Is the person on the ground?", "images/16.jpg", "Yes"],
[17, "Is blue a prominent color in the picture?", "images/17.jpg", "Yes"],
[18, "Does the image appear to be indoors?", "images/18.jpg", "Yes"],
[19, "Is the person on the ground?", "images/19.jpg", "Yes"],
[20, "Does the animal appear to be an alligator?", "images/20.jpg", "No"],
[21, "Does the person appear to be hunting?", "images/21.jpg", "Yes"],
[22, "Is the setting the desert?", "images/22.jpg", "No"],
[23, "Is there a car in the image?", "images/23.jpg", "No"],
[24, "Does the animal appear to be mating?", "images/24.jpg", "No"],
[25, "Is the person's shirt white?", "images/25.jpg", "Yes"],
[26, "Is there more than one person in the picture?", "images/26.jpg", "Yes"],
[27, "Does everybody appear to be standing?", "images/27.jpg", "Yes"],
[28, "Does the victim appear to be female?", "images/28.jpg", "No"],
[29, "Are two weapons visible in the image?", "images/29.jpg", "No"],
[30, "Is the body on the ground?", "images/30.jpg", "Yes"],
[31, "Is there a woman in the picture", "images/31.jpg", "No"],
[32, "Is either person wearing a red jacket?", "images/32.jpg", "No"],
[33, "Are there multiple people in the image?", "images/33.jpg", "Yes"],
[34, "Does the fighter appear to be holding a gun?", "images/34.jpg", "No"],
[35, "Does there appear to be a man throwing a punch?", "images/35.jpg", "Yes"],
[36, "Is there a man holding a bat?", "images/36.jpg", "Yes"],
[37, "Does the victim appear to be on the ground?", "images/37.jpg", "Yes"],
[38, "Is the victim being shot?", "images/38.jpg", "No"],
[39, "Does this scene appear to be a robbery?", "images/39.jpg", "Yes"],
[40, "Is this scene taking place outdoors?", "images/40.jpg", "No"],
[41, "Are there more than 3 people in the image?", "images/41.jpg", "Yes"],
[42, "Is the victim wearing a shirt?", "images/42.jpg", "No"],
[43, "Is there a tiger in the image", "images/43.jpg", "No"],
[44, "Do the people appear to be standing?", "images/44.jpg", "Yes"],
[45, "Does the victim appear to be fighting back?", "images/45.jpg", "No"],
[46, "Is the man holding a knife?", "images/46.jpg", "Yes"],
[47, "Is there a dog in the picture?", "images/47.jpg", "No"],
[48, "Are there two women in the picture?", "images/48.jpg", "No"],
[49, "Is there a pizza near the victim?", "images/49.jpg", "No"],
[50, "Do the people have blonde hair?", "images/50.jpg", "No"],
[51, "Is the man in the image getting kicked?", "images/51.jpg", "No"],
[52, "Is the woman in the image wearing a stripped shirt?", "images/52.jpg", "Yes"],
[53, "Does the woman appear to be yelling?", "images/53.jpg", "Yes"],
[54, "Does the perpetrator appear to be throwing a punch?", "images/54.jpg", "Yes"],
[55, "Is anybody in the picture swimming?", "images/55.jpg", "No"],
[56, "Is the image outdoors?", "images/56.jpg", "Yes"],
[57, "Is there a man in the picture?", "images/57.jpg", "No"],
[58, "Is this scene taking place in an elevator?", "images/58.jpg", "No"],
[59, "Is somebody in the image wearing black?", "images/59.jpg", "Yes"],
[60, "Does the victim appear to be shot?", "images/60.jpg", "No"]];

export default IMAGES;
